
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  adapter: postgresql
test:
  <<: *default
  adapter: postgresql

production:
  <<: *default
  adapter: postgresql


# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
# development:
#   <<: *default
#   adapter: sqlite3
# test:
#   <<: *default
#   adapter: sqlite3
#
# production:
#   <<: *default
#   adapter: sqlite3
